name: todoist_agent
description: "An AI Agent for managing your Todoist tasks"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  record: ^6.0.0
  path_provider: ^2.1.5
  wear: ^1.1.0
  audioplayers: ^6.0.0 # Add audioplayers dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
