name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install .
          
      - name: Create deployment script
        run: |
          cat > deploy.sh << 'EOL'
          #!/bin/bash
          set -e
          
          # Create app directory if it doesn't exist
          mkdir -p ~/my_server
          
          # Copy files
          cp -r ./* ~/my_server/
          
          # Install dependencies in a virtual environment
          cd ~/my_server
          python -m venv venv
          source venv/bin/activate
          pip install -e .
          
          # Create systemd service file
          cat > my_server.service << 'EOF'
          [Unit]
          Description=My FastAPI Server
          After=network.target
          
          [Service]
          User=$USER
          WorkingDirectory=/home/$USER/my_server
          ExecStart=/home/$USER/my_server/venv/bin/uvicorn my_server.main:app --host 0.0.0.0 --port 9090
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # Install and start service
          sudo mv my_server.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable my_server.service
          sudo systemctl restart my_server.service
          EOL
          chmod +x deploy.sh
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            mkdir -p ~/deploy_temp
            cd ~/deploy_temp
            rm -rf *
          
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "~/deploy_temp"
          
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ~/deploy_temp
            bash deploy.sh
            rm -f deploy.sh
