name: Deploy Server to VPS

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create deployment script
        run: |
          cat > deploy.sh << EOL
          #!/bin/bash
          set -e

          export PATH="\$PATH:\$HOME/.local/bin" # Escape $ for server execution

          rm -rf ~/todo_server

          cp -r todo_server ~/

          cd ~/todo_server
          uv venv --seed
          source .venv/bin/activate
          pip install -e . 

          echo "Creating .env file..."
          cat > .env << EOF_ENV
          OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
          GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
          TODOIST_API_KEY=${{ secrets.TODOIST_API_KEY }}
          ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}
          TODOIST_AGENT_ACCESS_KEY=${{ secrets.TODOIST_AGENT_ACCESS_KEY }}
          EOF_ENV
          echo ".env file created."

          # Create systemd service file
          echo "Creating systemd service file..."
          cat > todo_server.service << 'EOF_SERVICE' # Use quotes to prevent expansion here
          [Unit]
          Description=Todoist AI Server
          After=network.target

          [Service]
          # Run uvicorn from the todo_server directory where .env is located
          ExecStart=/home/root/todo_server/.venv/bin/uvicorn todo_server.src.main:app --port 9090
          WorkingDirectory=/home/root/todo_server # Set working directory for .env loading
          Restart=always

          # Optional: If environment variables need to be explicitly passed (dotenv usually handles this)
          # EnvironmentFile=/home/root/todo_server/.env

          [Install]
          WantedBy=multi-user.target
          EOF_SERVICE
          echo "Systemd service file created."

          # Install and start service
          echo "Installing and starting systemd service..."
          sudo mv todo_server.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable todo_server.service
          sudo systemctl restart todo_server.service
          echo "Service started."
          EOL
          chmod +x deploy.sh

      - name: Clean up VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/deploy_temp
            cd ~/deploy_temp
            rm -rf *
          
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "~/deploy_temp"
          
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/deploy_temp
            ./deploy.sh
