name: Deploy Server to VPS

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          cd todo_server
          uv venv
          uv pip install build
          uv pip install .
          
      - name: Create deployment script
        run: |
          cat > deploy.sh << 'EOL'
          #!/bin/bash
          set -e
          
          # Create app directory if it doesn't exist
          mkdir -p ~/todo_server
          
          # Copy files
          cp -r todo_server/* ~/todo_server/
          
          # Install dependencies in a virtual environment using uv
          cd ~/todo_server
          uv venv
          source .venv/bin/activate
          uv pip install -e .
          
          # Create systemd service file
          cat > todo_server.service << 'EOF'
          [Unit]
          Description=Todoist AI Server
          After=network.target
          
          [Service]
          User=$USER
          WorkingDirectory=/home/$USER/todo_server
          ExecStart=/home/$USER/todo_server/.venv/bin/uvicorn todo_server.src.main:app --host 0.0.0.0 --port 9090
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # Install and start service
          sudo mv todo_server.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable todo_server.service
          sudo systemctl restart todo_server.service
          EOL
          chmod +x deploy.sh
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/deploy_temp
            cd ~/deploy_temp
            rm -rf *
          
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "~/deploy_temp"
          
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ~/deploy_temp
            bash deploy.sh
            rm -f deploy.sh
