name: Deploy Server to VPS

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create deployment script
        run: |
          cat > deploy.sh << 'EOL'
          #!/bin/bash
          set -e

          export PATH="$PATH:$HOME/.local/bin"
          
          # Cleanup
          rm -rf ~/todo_server
          
          # Copy files
          cp -r todo_server ~/
          
          # Install dependencies in a virtual environment
          cd ~/todo_server
          uv venv --seed
          source .venv/bin/activate
          pip install -e .
          
          # Create systemd service file
          cat > todo_server.service << 'EOF'
          [Unit]
          Description=Todoist AI Server
          After=network.target
          
          [Service]
          User=$USER
          WorkingDirectory=/home/$USER/todo_server
          ExecStart=/home/$USER/todo_server/.venv/bin/uvicorn todo_server.src.main:app --host 0.0.0.0 --port 9090
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # Install and start service
          sudo mv todo_server.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable todo_server.service
          sudo systemctl restart todo_server.service
          EOL
          chmod +x deploy.sh
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/deploy_temp
            cd ~/deploy_temp
            rm -rf *
          
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "~/deploy_temp"
          
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/deploy_temp
            ./deploy.sh
